### ISSUE TITLE
Throw error if invalid arguments or arguments not available

### ISSUE THREAD

**Issue by funkill** [1000ch/node-github-markdown#5]
If i put wrong argument or don't put any arguments to executable, throws errors:

```bash
# ghmd --help # or only `ghmd`
/usr/lib64/node_modules/github-markdown/cli.js:13
  throw new Error('There is no arguments.');
        ^
Error: There is no arguments.
    at Object.<anonymous> (/usr/lib64/node_modules/github-markdown/cli.js:13:9)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:124:18)
    at node.js:882:3
```

**Comment by 1000ch** [comment]
@funkill Thank you for reporting.
This is fixed at `v1.0.0`, so please try it :)
